classDiagram

	class Utenti{

	nominativo 
	listaPrenotazioni 
	listaPrestiti 
	email
	passWord 

	}

	class Opere{ 
	
	titolo 
	isbn 
	autori 
	generi 
	dataPubblicazione 
	isDisp 
	numPagine 
	numOpereDisponibili 

	}

	class RegistroUtenti{

	listaUtenti 

	}

	class Catalogo{

	listaOpere

	}
