classDiagram

	class Prestito
		<<entity>>

		- libroPrestito : Libro
		- dataPrestito : Data
		- dataScadenza : Data
		- dataRestituzione : Data
		- status : String
		- penale : int

		+ setLibroPrestito(nuovoLibro : Libro) void
		+ getLibro() Libro
		+ setDataPrestito(nuovaData : Data) void
		+ getDataPrestito() Data
		+ setDataScadenza(nuovaData : Data) void
		+ getDataScadenza() Data
		+ setDataRestituzione(nuovaData : Data) void
		+ getDataRestituzione() Data
		+ setStatus(nuovoStatus : String) void
		+ getStatus() String
		+ isScaduto() bool
		+ setPenale(nuovaPenale : int) void
		+ getPenale() int

	class Utente
		<<entity>>

		- nominativo : String
		- codUtente : int
		- email : String
		- password : String
		- listaLibriPrestito : List~Prestito~

		+ setNominativo(nuovoNom : Stringa) void
		+ getNominativo() String
		+ setCodUtente(nuovoCod : int) void
		+ getCodUtente() String
		+ setEmail(nuovaEmail : String) void
		+ getEmail() String
		+ setPassword(nuovaPass) void
		+ getPassword() String

		+ appendiPrestito(p : Prestito) void
		+ estraiPrestito() Prestito
		+ rimuoviPrestito() void
		%%+ cercaPrestito() void
		+ ordinaPrestiti() void

	class Libro
		<<entity>>

		- titolo : String
		- genere : String
		- isbn : String
		- pagine : int
		- numCopieDisp : int

		+ setTitolo(nuovoTitolo : String) void
		+ getTitolo() String
		+ setGenere(nuovoGenere : String) void
		+ getGenere() String
		+ setIsbn(nuovoIsbn : String) void
		+ getIsbn() String
		+ setPagine(nuovePagine : int) void
		+ getPagine() int
		+ isDisponibile() bool
		+ setnumCopieDisp(nuovoNum : int) void
		+ getnumCopieDisp() int

	class RegistroUtenti
		<<entity>>

		- registro : List~Utente~

		+ aggiungiUtente() void
		+ estraiUtente() Utente
		+ rimuoviUtente() void
		+ cercaUtente(email : String) void
		+ ordinaUtenti() void
		%%+ 
		%%+ 
		%%+ 
		%%+ 

	class Catalogo
		<<entity>>

		- depLibri : List~Libro~

		+ aggiungiLibro(l : Libro) void
		+ estraiLibro() Libro
		+ rimuoviLibro() void
		+ cercaLibro(isbn : String) void
		+ ordinaLibri() void
		%%+ 
		%%+ 
		%%+ 
		%%+ 

	class Console
		<<control>>

		- regUt : RegistroUtenti
		- cat : Catalogo

		- utLog : Utente
		- libPrestito : libroPrestito
		- p : Prestito

		+ creaUtente(nominativo : String, email : String, password : String) bool
		+ salvaUtente(u) void
		+ modificaUtente() void
		+ eliminaUtente() bool
		%%+ richiediUtente()

		+ creaPrestito(t : String, isbn : String, genere : String) bool
		+ salvaPrestito(p : Prestito,l : Libro) bool
		+ modificaPrestito() void
		+ eliminaPrestito(email : String) bool
		+ trovaPrestito(isbn : String) void

	class UI
		<<boundary>>

		- c : Console

		%% utente
		+ registraAccount() void
		+ aggiornaAccount() void
		+ eliminaAccount() void
		+ login() void

		+ effettuaPrestiti() void
		+ aggiornaPrestiti() void
		+ cancellaPrestiti() void

		%% comunicazione input-output

		+ msgBenvenuto() void
		+ msgModAutenticazione() void
		+ msgRichiestaAutenticazione() void

		+ msgRichiestaCredenzialiReg() void
		+ msgRichiestaCredenzialiLogin() void

		+ msgRichiestaRisposta() void
		+ msgRispostaNonValida() void
		+ msgRichiestaRispostaValida() void

		+ msgRegistrazioneSucc() void
		+ msgRegistrazioneFallita() void

		+ msgMostraOpzioni() void
		+ msgRichiestaOpzione() void

		+ msgRichiestaCredenzialiLibro() void
		+ msgMostraLibroTrovato() void
		+ msgRichiestaConfermaPrestito() void
		+ msgPrestitoSalvato() void
		+ msgPrestitoNonSalvato() void

		+ msgAccountSalvato() void
		+ msgLoginSuccesso() void
		+ msgLoginFallito() void

		+ inserisceAutenticazione() String
		+ inserisceCredenzialiReg(nominativo : String, email : String, password : String) void
		+ inserisceCredenzialiLogin(email : String, password : String) void
		+ inseriscePassword() String

		+ inserisceOpzione() String

		+ inserisceRisposta() String
		+ inserisceCredenzialiLibro(titolo : String, isbn : String, genere : String) void







