```mermaid

classDiagram
	class Prestito
		libroPrestito
		dataPrestito
		dataScadenza
		dataRestituzione
		status
		penale

	class Utente
		nominativo
		codUtente
		email
		password
		listaPrestiti

	class Libro
		titolo
		genere
		isbn
		pagine
		numCopieDisp

	class RegistroUtenti
		registro

	class Catalogo
		depLibri

	class Data
		giorno
		mese
		anno






