sequenceDiagram
	actor User

	participant UI
	participant Console

	participant Store

	participant Utente
	participant Carrello
	participant Ordine
	participant Prodotto

	User->>+UI:cercaProdotto()
	UI->>User: Richiede credenziali prodotto
	User->>UI: Inserisce credenziali prodotto
	UI->>+Console:trovaProdotto(codice)

	loop per ogni Prodotto in Store.catalogo and codice != Prodotto.codice
		opt codice == Prodotto.codice
			Console-->>-UI: return true
		end
	end

	UI-->>User: Richiede conferma di aggiunta del prodotto al carrello
	User->>UI: Inserisce risposta

	alt risposta == "si"
		UI->>+Console: salvaProdottoCarrello(Prodotto)
		Console->>+Carrello: appendiProdotto(Prodotto)
		Carrello->>-Console: Prodotto aggiunto
		Console-->>-UI: Prodotto salvato
		UI-->>-User: stampa messagggio "Prodotto aggiunto al carrello"
	else
		UI->>+Console: distruggiProdotto_temporaneo()
		Console-->>-UI: Prodotto distrutto
		UI-->>-User: stampa messaggio "Prodotto non aggiunto al carrello"
	end
